[package]
name = "s11_a02_cruzamento"
version = "0.1.0"
edition = "2021"
authors = ["Rômulo Silva de Oliveira"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
device_query = "1.1.3"
